---
apiVersion: v1
kind: Secret
metadata:
  name: namespace-namespace-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/namespace-gateway-gitops
